### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Hare8563** [Hare8563/SpzDocker#3]

**Comment by Hare8563** [comment]
docker run --rm -v "$PWD":/usr/src/rails-server -w /usr/src/rails-server author/rails-server:latest /bin/bash -c "bundle exec rails new myapp -T -f --webpack=react --database=mysql --skip-coffee --skip-sprockets && cd myapp && bundle exec rake webpacker:install && bundle exec rake webpacker:install:react && bundle exec rake webpacker:install:typescript"

**Comment by Hare8563** [comment]
docker run --rm -v "$PWD":/usr/src/rails-server -w /usr/src/rails-server author/rails-server:latest

**Comment by Hare8563** [comment]
```
FROM ruby:2.5.3

ENV APP_DIR /usr/src/myapp

RUN mkdir -p ${APP_DIR}

WORKDIR $APP_DIR

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs mysql-client && \
    npm install -g yarn

COPY . $APP_DIR
RUN bundle install --path vendor/bundle
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
```

**Comment by Hare8563** [comment]
`docker run -p 3000:3000 author/runner:latest`

**Comment by Hare8563** [comment]
```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>
```

**Comment by Hare8563** [comment]
docker-compose up

**Comment by Hare8563** [comment]
```
version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3306:3306
    networks:
      - default
  web:
    environment:
      - MYAPP_DATABASE_PASSWORD=mysql
      - MYAPP_DATABASE_HOST=db
    build: rails-app/myapp
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - db
networks:
  default:
    driver: bridge
```
